### PR TITLE
Setup embedded tracker environment correctly in queuedtracking:process

### LINKED ISSUE #12: Command line processing causing exception
Hi,

I'm running into an issue with the current version of the plugin. I configured Piwik 2.14.0-rc1 and QueuedTracking version 0.1.6, setup Redis and the plugin configuration and noticed that everything is being collected perfectly. However, once I switch Process during tracking request off and try to process the queue using the console, I get the following exception:

**[Piwik\Container\ContainerDoesNotExistException] The root container has not been created yet.**

Looking at the code, it seems it is caused in Factory.php *(StaticContainer::get('Piwik\Plugins\QueuedTracking\Settings');)* because all the other commands work as expected like queuedtracking:monitor

Cheers,
Jesper

### PR DESCRIPTION
**Pull request by diosmosis**
Use Environment instance instead of trying to clear the container and reload tracker plugins / environment in-place.

Should fix #12 

@tsteur Can you test these changes? I'm not currently setup to test/debug QueuedTracking and there aren't any automated tests for this command. Feel free to commit directly to this branch, you'd know better how to apply this change to this plugin.

### CODE REVIEW

File: Commands/Process.php [hunk 1]
```diff
@@ -37,13 +35,15 @@ protected function execute(InputInterface $input, OutputInterface $output)
         $systemCheck = new SystemCheck();
         $systemCheck->checkRedisIsInstalled();
 
-        Access::getInstance()->setSuperUserAccess(false);
-        Plugin\Manager::getInstance()->setTrackerPluginsNotToLoad(array('Provider'));
+        $trackerEnvironment = new Environment('tracker');
```
Comment (tsteur) [inline Commands/Process.php]: Will this recreate the container and clear any previous created instances? Especially re the Cache? I'm not into the environment / container code so just asking :)

Comment (diosmosis) [inline Commands/Process.php]: it doesn't recreate the container, it creates a new one w/ the tracker environment. For now, this pushes a container instance onto a stack so StaticContainer::get() will use the top. Which I think means I missed something, there should probably be a `$trackerEnvironment->destroy()` call after processing is done, so control goes back to the CLI environment.

Note: This means there's a new Plugin\Manager and should be new Plugin instances stored in `$trackerEnvironment`. Since it's only done once here, shouldn't be an issue.

Eventually, we'll get rid of StaticContainer so everything is provided through DI, then we just use the environment directly and worry about nothing.

**Comment by ldidry** [comment]
I tested the patch. It's still not working. I got the following error:
```
PHP Fatal error:  Call to undefined method Piwik\Plugins\QueuedTracking\Queue\Manager::shouldRecordStatistics() in /var/www/piwik/plugins/QueuedTracking/Queue/Processor.php on line 68
```

File: Commands/Process.php (hunk 1 above)
Comment (tsteur) [inline Commands/Process.php]: Looks like this PR will fix a couple of issues. 

> Which I think means I missed something, there should probably be a $trackerEnvironment->destroy() call after processing is done, so control goes back to the CLI environment.

Does this mean there's more work left?

Comment (diosmosis) [inline Commands/Process.php]: Should be done w/ my last commit.

**Comment by diosmosis** [comment]
@ldidry fixed that error in my last commit.

**Comment by ldidry** [comment]
This error is fixed, indeed. But there is another problem: I got 534455 requests to process (said queuedtracking:monitor) but when I launch the process command, it says:

```
  This worker finished queue processing with 0req/s (0 requests in 0.00 seconds) 
```

**Comment by tsteur** [comment]
Thx @diosmosis It looks like it works now, tested as well. Also seems to use the right environement/cache (which is important for performance etc)

**Comment by diosmosis** [comment]
@tsteur Would you know why @ldidry might be getting the error he mentioned? Do you think it might have something to do w/ DI (ie, wrong instance being used somewhere), or something else?

**Comment by tsteur** [comment]
It worked for me. @ldidry are you still getting this error with latest version (0.1.7)? Can you maybe update to 2.14.2?

**Comment by ldidry** [comment]
I just upgraded both piwik and plugin to 2.14.2 and 0.1.7 this morning and this is working. Thanks a lot! :beers:

**Comment by tsteur** [comment]
Thx! I haven't tested with Piwik 2.14.0 so I'm not sure whether plugin will work with that version. I'll release a new version 0.1.8 that requires Piwik 2.14.2 just to make sure it'll work
