### PR TITLE
disable monitor interactive paging on windows #269

### LINKED ISSUE #269: Fatal queuedtracking:monitor issue
**Error:**

    ERROR     [2024-10-21 13:39:35] 5424  Uncaught exception: Error: Call to undefined function Piwik\Plugins\QueuedTracking\Commands\readline_callback_handler_install() in matomo\plugins\QueuedTracking\Commands\Monitor.php:74

**Platform:**
Windows Server 2022
PHP x64 8.3.10
Matomo 5.1.1
Queued Tracking 5.1.0

**Issue:**
Windows PHP **DOES NOT** ship with `readline_callback_handler_install()`; contrary to the claim made at https://www.php.net/manual/en/readline.installation.php

**PHP Versions tested:**
7.1.0 x64
7.4.9 x64
8.1.9 x64
8.3.10 x64
8.3.12 x64

**Additional resources**
https://stackoverflow.com/a/71178783

### PR DESCRIPTION
**Pull request by haristku**
### Description:
disable monitor interactive paging on Windows environment 
Fixes: #269 

this PR will cause the monitor feature to have different behaviour between Windows and Linux.
please advise, are these different conditions allowed or not? if not allowed, i will adjust the code to remove the interactive paging feature altogether.

---

- the new `-r` parameter replace the old `-p`
- while `-p` now used to jump to specific page

**for example (if we have 16 queue workers):**
-  `php console queuedtracking:monitor` will display 16 rows per page (only 1 page)
- `php console queuedtracking:monitor -r 3` will display 3 rows per page (6 pages total)
- `php console queuedtracking:monitor -r 3 -p 2`  will display 3 rows per page and jump to 2nd page
- `php console queuedtracking:monitor -r 3 -p 6`  will display 3 rows per page and jump to 6th page

`-r` and `-p` will work both on Windows or Linux, but only Linux has the ability to move pages interactively.

@AltamashShaikh @snake14 do you have any other suggestions?

### CODE REVIEW

File: Commands/Monitor.php [hunk 1]
```diff
@@ -212,21 +220,57 @@ private function getIterationsFromArg()
...
+        return $perPage;
+    }
+
+    /**
+     *
+     * @return bool
+     */
+    private function interactiveCapability()
+    {
+        if (str_starts_with(strtoupper(PHP_OS), 'WIN')) {
```
Comment (AltamashShaikh) [inline Commands/Monitor.php]: @haristku Can you simplify this function to
```suggestion
        return function_exists('readline_callback_handler_install');
```

**Review by AltamashShaikh — CHANGES_REQUESTED** [review]
@haristku Requested 1 change rest looks good to me :+1:

**Comment by haristku** [comment]
done.. 👍 
ty.

**Review by snake14 — APPROVED** [review]
Looks good. I didn't find any issues in my testing. Nice work! :+1: 

I didn't see any validation for a page number higher than there are pages, but it simply returns the last page when I tried it. I think that works fine.

**Review by AltamashShaikh — APPROVED** [review]
